CREATE TABLE IF NOT EXISTS account
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    usd_balance DECIMAL(20, 2),
    btc_balance DECIMAL(20, 8),
    version     BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS trade_order
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT,
    price_limit DECIMAL(20, 2),
    amount      DECIMAL(20, 8),
    status      VARCHAR(50),
    created_at  TIMESTAMP,
    version     BIGINT DEFAULT 0
);